# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
