apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: websecure
      port: 443
      targetPort: 8443 # Typically Traefik's HTTPS port, may need adjustment
      nodePort: 30443
