apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 8000 # <== FIXED: actual HTTP port inside the container
      nodePort: 30080
    - name: websecure
      port: 443
      targetPort: 8443 # <== Optional: change only if Traefik uses HTTPS
      nodePort: 30443
