# This file defines a Traefik Middleware that strips the /api prefix from requests
# to the backend service, allowing the frontend service to handle requests without the /api prefix.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kubevisualizer-strip-api
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /api
